jobs:
  - file: /var/jenkins_home/job-dsl/folders.groovy
  - file: /var/jenkins_home/job-dsl/seed.groovy
  - file: /var/jenkins_home/job-dsl/projects/xhsmedium-ci.groovy
  - file: /var/jenkins_home/job-dsl/projects/xhsmedium-regression.groovy
  - file: /var/jenkins_home/job-dsl/projects/xhsmedium-release.groovy
  - file: /var/jenkins_home/job-dsl/projects/xhsmedium-deploy.groovy
  - file: /var/jenkins_home/job-dsl/projects/runtime-maintenance.groovy

unclassified:
  globalLibraries:
    libraries:
      - name: "jenkins-platform-library"
        defaultVersion: "main"
        implicit: false
        allowVersionOverride: false
        includeInChangesets: true
        retriever:
          modernSCM:
            libraryPath: "shared-library"
            scm:
              git:
                id: "jenkins-platform-library"
                remote: "${JENKINS_LIBRARY_URL}"
