jenkins:
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "admin"
          name: "Local Platform Administrator"
          password: "${trim:${readFile:/run/secrets/jenkins_admin_password}}"
        - id: "audit"
          name: "Local Read-only Auditor"
          password: "${trim:${readFile:/run/secrets/jenkins_audit_password}}"

