plugins {
    id 'groovy'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation localGroovy()
    testImplementation 'com.lesfurets:jenkins-pipeline-unit:1.1'
    testImplementation 'junit:junit:4.13.2'
}

sourceSets {
    main {
        groovy {
            srcDirs = ['vars', 'src']
        }
    }
    test {
        groovy {
            srcDirs = ['test']
        }
    }
}

test {
    testLogging {
        events 'passed', 'failed', 'skipped'
    }
}
